server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-very-long-secret-key-at-least-256-bits-for-hs256-algorithm
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
